disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Portfolio"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "test.png"
description = "Portfolio for Seamus Mullan"

[[params.author.links]]
github = "https://github.com/seamusmullan"

[[params.author.links]]
linkedin = "https://linkedin.com/seamusmullan"

["params.author"]
name = "Seamus Mullan"
bio = "Passionate developer with interests in Signal Processing, Algorithmic Trading, Music Production and Game Development"
